require_relative './verb/classification_types'
require_relative './verb/constants'
require_relative './verb/irregulars'
require_relative './verb/phonographia'
require_relative './verb/tense_definitions'
require_relative './verb/verb_types'
require_relative './verb/deserializer'
