require_relative './components/chart_presenter'
require_relative './components/infinitivizer'
require_relative './components/classifier'
require_relative './components/principal_parts_extractor'
require_relative './components/type_evaluator'
require_relative './components/participler'
require_relative './components/validator'
require_relative './components/vector_applicator'
