require_relative 'tense_definitions/irregular'
require_relative 'tense_definitions/impersonal'
require_relative 'tense_definitions/first'
require_relative 'tense_definitions/second'
require_relative 'tense_definitions/third'
require_relative 'tense_definitions/third_io'
require_relative 'tense_definitions/fourth'
